[package]
name = "tcalc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarantool = "0.6.0"
serde = "1.0"

[lib]
crate-type = ["lib", "cdylib"]
